/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * @file    main.c
 * @brief	Main entry point for waveform generation.
 *
 * @author  Venetia Furtado
 * @date    11/18/2025
 * References:
 * 1. https://github.com/alexander-g-dean/ESF/tree/master/ST/Code/ch6
 * 2. Embedded Systems Fundamentals with Arm Cortex-M based Microcontrollers (Chapters 6 and 9) - Alexander Dean
 * 3. RM0091 Reference manual - Chapter 10 (DMA), Chapter 13 (ADC), Chapter 14 (DAC), Chapter 21(TIM6/TIM7)
 * 4. RM0091 Reference manual - Appendix code examples
 * 5. https://blog.embeddedexpert.io/?p=1196
 * 6. https://community.st.com/t5/stm32-mcus-products/problem-with-dac-dma-end-of-transmission-interrupts-on/td-p/756774
 * 
 **/

#include <stdio.h>
#include "spi.h"
#include "i2c.h"
#include "bme280.h"
#include "switch.h"
#include "fsm.h"
#include "data_acquisition.h"
#include "systick.h"

#define WAIT_TIME_PER_ITERATION          (3000)


void delay(volatile unsigned int time_del)
{
   //INFO_LOG("Starting delay timer for %d ms", time_del);
        volatile int n;
        while (time_del--)
        {
                n = WAIT_TIME_PER_ITERATION; /*No. of iterations to give approximate delay in order of milliseconds*/
                while (n--);
        }
}

FSMInfo info;

/**
 * @brief 	Initializes all peripherals required for waveform generation and analog
 * 			sampling. Once initialization is complete, the function enters an infinite loop 
 * 			where analog_in() is repeatedly called to process incoming analog signals.
 *
 */
int main(void)
{
	Init_SPI2();
	BME280_Init();
	init_switch();
	Init_DataAcquisition();
	Init_FSM(&info);
	init_systick();

	printf("hello world!!\n\r");

	ticktime_t tick_counter = 0;

	while (1)
	{
		/*do not run fsm if INTERVAL_MS has not occured*/
		if (tick_counter != get_current_tick())
		{
			Handle_FSM(&info);
			tick_counter = get_current_tick();
		}
		/*do other work here*/
	}


#if 0
	while (1)
	{
		printf("SPI = %x\n\r", SPI_Read(0xD0));
		BME280_Data data;

		BME280_ReadAll(&data);

		printf("Read values: Temp %f Pressure %f Humidity %f\n\r",
				 data.temperature,
				 data.pressure,
				 data.humidity);

		delay(1000);
	}
#endif
#if 0
	I2C_Init();
	delay(500);
	uint8_t read_val = 0;
	printf("\rhello world!!\n\r");
	while(1)
	{
		I2C_WriteReg(0x76, 0xD0, &read_val, 1);

		//I2C_ReadReg(0x76, 0xD0, &read_val, 1);
		//printf("I2C = %x\n\r", read_val);
		delay(500);
	}
#endif

#if 0
	i2cInitGpio();
	delay(500);
	uint8_t read_val = 0;
	printf("\rhello world!!\n\r");

	sendControlByte(READ, 0xEC);
	read_val = i2cByteRead();
	// i2cByteWrite(0x76, 0xD0, &read_val, 1);

	// I2C_ReadReg(0x76, 0xD0, &read_val, 1);
	printf("I2C = %x\n\r", read_val);
	delay(500);
	while(1);
#endif
	return 0;
}
