/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/**
 * @file    main.c
 * @brief	Entry point of the BME280 Weather Station application.
 *
 * @author  Venetia Furtado
 * @date    12/02/2025
 * References:
 * 1. https://github.com/alexander-g-dean/ESF/tree/master/ST/Code/
 * 2. Embedded Systems Fundamentals with Arm Cortex-M based Microcontrollers - Alexander Dean
 * 3. RM0091 Reference manual
 * 4. RM0091 Reference manual - Appendix code examples
 * 5. BME280 Datasheet
 * 
 **/
#include <stdio.h>
#include "spi.h"
#include "i2c.h"
#include "bme280.h"
#include "switch.h"
#include "fsm.h"
#include "data_acquisition.h"
#include "systick.h"
#include "pwm.h"
#include "log.h"
#include "timer.h"


/**
 * @brief 	Entry point of the BME280 Weather Station application.
 * 
 * This function initializes all required hardware peripherals,
 * configures the system resources, and starts the finite state
 * machine (FSM). Depending on the build configuration, it sets up
 * either SPI or I2C communication for the BME280 sensor.
 *
 */
int main(void)
{
#ifdef RUN_WITH_SPI
	Init_SPI2();
#else
	I2C_Init();
#endif
	PWM_Init();
	BME280_Init();
	Init_switch();
	Init_DataAcquisition();
	Init_FSM();
	init_systick();
	Init_TIM7();
	STATE_TRANSITION_LOG("NORMAL state");
	run_FSM();

	return 0;
}
